<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>GarrisonDrills</AssemblyName>
    <RootNamespace>GarrisonDrills</RootNamespace>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>11.0</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <BannerlordBin Condition=" '$(BannerlordBin)' == '' ">E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client</BannerlordBin>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="TaleWorlds.CampaignSystem">
      <HintPath>$(BannerlordBin)\TaleWorlds.CampaignSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.Localization">
      <HintPath>$(BannerlordBin)\TaleWorlds.Localization.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.Library">
      <HintPath>$(BannerlordBin)\TaleWorlds.Library.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.MountAndBlade">
      <HintPath>$(BannerlordBin)\TaleWorlds.MountAndBlade.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.Core">
      <HintPath>$(BannerlordBin)\TaleWorlds.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.ObjectSystem">
      <HintPath>$(BannerlordBin)\TaleWorlds.ObjectSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
