<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>9</LangVersion>
    <AssemblyName>RBMPlayerStaminaPoiseBuff</AssemblyName>
    <RootNamespace>RBMPlayerStaminaPoiseBuff</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Configurations>Debug;Release</Configurations>
    <BannerlordBin Condition=" '$(BannerlordBin)' == '' ">E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client</BannerlordBin>
    <WorkshopRoot Condition=" '$(WorkshopRoot)' == '' ">E:\SteamLibrary\steamapps\workshop\content\261550</WorkshopRoot>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="TaleWorlds.Core">
      <HintPath>$(BannerlordBin)\TaleWorlds.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.Library">
      <HintPath>$(BannerlordBin)\TaleWorlds.Library.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.MountAndBlade">
      <HintPath>$(BannerlordBin)\TaleWorlds.MountAndBlade.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.DotNet">
      <HintPath>$(BannerlordBin)\TaleWorlds.DotNet.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.Engine">
      <HintPath>$(BannerlordBin)\TaleWorlds.Engine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(WorkshopRoot)\2859188632\bin\Win64_Shipping_Client\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="RBMAI">
      <HintPath>$(WorkshopRoot)\2859251492\bin\Win64_Shipping_Client\RBMAI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
